In [1]:
# Topics covered:
#     copy    
#         Shallow copy 
#         Deep copy 


In [2]:
import numpy as np 

In [3]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [4]:
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [5]:
a[0] = 23
a

array([23,  2,  3,  4])

In [6]:
b

array([[23,  2],
       [ 3,  4]])

In [7]:
np.shares_memory(a,b) # Shallow copy    

True

In [10]:
#eg 2

In [11]:
c = a 
c

array([23,  2,  3,  4])

In [12]:
a[2] = 56
a

array([23,  2, 56,  4])

In [14]:
c # shallow copy

array([23,  2, 56,  4])

In [15]:
np.shares_memory(c,a)

True

In [20]:
# eg 3:

a = np.arange(1,11)
b = a[::2] # Slicing --> Shallow copy

In [21]:
b

array([1, 3, 5, 7, 9])

In [22]:
a[0] = 90

In [23]:
b

array([90,  3,  5,  7,  9])

In [24]:
np.shares_memory(a,b)

True

In [25]:
a[1] = 70

In [26]:
a

array([90, 70,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
b

array([90,  3,  5,  7,  9])