In [1]:
import numpy as np

In [3]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [4]:
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56


In [5]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6  8  7 28 56 19]]


In [2]:
import numpy as np 
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[1,2]

6

In [7]:
arr_1 = np.arange(1,10)
arr_1[[1,3,5,7]]

array([2, 4, 6, 8])

In [9]:
#Multi-indexing in 2D array

array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array[[0,0],[1,1]]

array([2, 2])

In [18]:
# to pint all the diagonal elements in an array
print('Diagonal elements in an array')
array[[0,1,2],[0,1,2]]

Diagonal elements in an array


array([1, 5, 9])

In [22]:
#slicing of an array
a = np.arange(11,20).reshape(3,3)
a[:2] # prints first 2 rows
a[:]  #print all rows

a[:,:2] # prints all rows with two columns
# array_name[R, C]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [23]:
a[:,1:3]

array([[12, 13],
       [15, 16],
       [18, 19]])

In [28]:
# Fancy Indexing in 2D

a<15

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [27]:
a[a>15]

array([16, 17, 18, 19])

In [29]:
np.sum(a)

135

In [30]:
np.mean(a)

15.0

In [32]:
np.min(a)

11

In [33]:
np.max(a)

19

In [34]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [35]:
np.mean(a,axis=0) #Vertical mean

array([14., 15., 16.])

In [36]:
np.mean(a,axis=1) # Horizontal axis

array([12., 15., 18.])

In [37]:
x = np.arange(1,10)

In [38]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [40]:
np.all(a<2)

False

In [42]:
np.any(x<5)

True

In [45]:
a = np.arange(1,5)
b = np.arange(3,7)
# Both the size of the arrays must be same 
# if not error occurs

a+b

array([ 4,  6,  8, 10])

In [47]:
# update array base on some conditions

arr = np.arange(-5,10)
arr[arr<0] = -1
arr[arr>0] = 1
arr

array([-1, -1, -1, -1, -1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [49]:
# Where fucntion used to apply condition for certain numpy arrray

# np.where(condition,[x,y])

np.where(arr>=0,'+ve','-ve')


array(['-ve', '-ve', '-ve', '-ve', '-ve', '+ve', '+ve', '+ve', '+ve',
       '+ve', '+ve', '+ve', '+ve', '+ve', '+ve'], dtype='<U3')

In [55]:
# use Case Tutorials

np_arr = np.loadtxt(r'D:\Vs_Code_Directory\Python\Scalar\DAV1\NUMPY-2UseCase.txt',dtype='str')
np_arr

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [61]:
series_Date = np_arr[:,0]
series_Date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [67]:
Trasnpose = np_arr.T # Transpose of that series

In [63]:
np_arr.shape

(96, 6)

In [72]:
Mood = Trasnpose[2]

In [73]:
step_count = Trasnpose[1]

In [74]:
step_count_Mood_Happy = step_count[Mood=='Happy']

In [75]:
step_count_Mood_Happy

array(['4732', '330', '4550', '4435', '4779', '1831', '2255', '539',
       '5464', '4068', '4683', '4033', '6314', '614', '3149', '4005',
       '4880', '4136', '705', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '3608', '774', '1421', '4064', '2725',
       '5934', '1867', '7422', '5537', '5376', '153', '2203'],
      dtype='<U10')

In [77]:
int_SCMH = np.array(step_count_Mood_Happy,dtype = 'int')

In [78]:
np.unique(int_SCMH)

array([ 153,  269,  330,  493,  539,  546,  614,  705,  774,  995, 1421,
       1831, 1867, 2203, 2255, 2725, 3149, 3608, 4005, 4033, 4064, 4068,
       4136, 4275, 4421, 4435, 4550, 4683, 4732, 4779, 4880, 5195, 5376,
       5464, 5537, 5934, 5999, 6314, 6930, 7422])

In [79]:
np.mean(int_SCMH)

3392.725

In [86]:
Happy_Neutral = step_count[(Mood == 'Happy') | (Mood=='Neutral')]

In [87]:
np.mean(np.array(Happy_Neutral,dtype='int'))

3296.4328358208954

In [89]:
Happy = np.mean(np.array(Mood=='Happy',dtype='int'))
Sad = np.mean(np.array(Mood=='Sad',dtype='int'))
print(Happy,Sad)

0.4166666666666667 0.3020833333333333
