In [3]:
import numpy as np

In [4]:
lst = list(range(1000))
len(lst)

1000

In [5]:
%timeit [i**2 for i in lst]

45.9 µs ± 5.97 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
b = np.array(lst)

In [9]:
print(b**2)
%timeit b**2

[     0      1      4      9     16     25     36     49     64     81
    100    121    144    169    196    225    256    289    324    361
    400    441    484    529    576    625    676    729    784    841
    900    961   1024   1089   1156   1225   1296   1369   1444   1521
   1600   1681   1764   1849   1936   2025   2116   2209   2304   2401
   2500   2601   2704   2809   2916   3025   3136   3249   3364   3481
   3600   3721   3844   3969   4096   4225   4356   4489   4624   4761
   4900   5041   5184   5329   5476   5625   5776   5929   6084   6241
   6400   6561   6724   6889   7056   7225   7396   7569   7744   7921
   8100   8281   8464   8649   8836   9025   9216   9409   9604   9801
  10000  10201  10404  10609  10816  11025  11236  11449  11664  11881
  12100  12321  12544  12769  12996  13225  13456  13689  13924  14161
  14400  14641  14884  15129  15376  15625  15876  16129  16384  16641
  16900  17161  17424  17689  17956  18225  18496  18769  19044  19321
  1960

In [11]:
b.ndim


1

Numpy vs list

We can store only one data type in numpy array.
Whereas in list we can store multiple datatypes.


<img src="https://drive.google.com/uc?id=1lgwART77tbifHMJjw-d4NV7aEpr0LVat">

In [20]:
import numpy as np
# specifying the datatype of the numpy array with dtype
a = np.array([1,2,3,4,'AAJ'],dtype='str') 
int_arr = np.array([700,90,56,23])
print(int_arr)
print(a)
# How to see the dimesion of the array
print(a.ndim)
# How to see the shape of the array ?
# It return the tupele of the rows and columns
print(a.shape)
# to see the data type of a particular variable
print(type(a))
# to convert a numpy array from integer to float or vice versa
as_typ = int_arr.astype("float")
print(as_typ)

[700  90  56  23]
['1' '2' '3' '4' 'AAJ']
1
(5,)
<class 'numpy.ndarray'>
[700.  90.  56.  23.]


<img src="https://drive.google.com/uc?id=1GSV_E1CaCc_Ur7pWJ-Kqv0VKvBRwByR1">

In [24]:
range_fn = list(range(2,40,2))
print(range_fn)
# Same functionality 
arange_fn = np.arange(29,67,2)
print(arange_fn)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
[29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65]


Access using the index 

In [26]:
b = np.array([1,2,12,3,4,5,6,7,8,9])
print(b[4])
# negative indexing
print(b[1])

4
2


In [28]:
# List slicing

print(b[3:])
print(b[:4])

[3 4 5 6 7 8 9]
[ 1  2 12  3]


In [29]:
arr = np.arange(5)
arr[2:4] = 23
print(arr)

[ 0  1 23 23  4]


In [30]:
# multi indexing

x = np.arange(1,15,2)
print(x)



[ 1  3  5  7  9 11 13]


In [31]:
print(x[[2,6]])
print(x[[5,2,4]])


[ 5 13]
[11  5  9]


In [34]:
# Fancy Indexing --> Masking

a = np.array([2,5,3,6,4,8,1,9])
print(a)

print(a[a<6])
print(a<6)

[2 5 3 6 4 8 1 9]
[2 5 3 4 1]
[ True  True  True False  True False  True False]


In [38]:
print(a[a%2 == 0])
a[True]

[2 6 4 8]


array([[2, 5, 3, 6, 4, 8, 1, 9]])

In [39]:
#Quiz1
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)
#Quiz2
import numpy as np
arr = np.arange(5)
arr[2:4] = 0
print(arr)
#Quiz3
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)
#Quiz4
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]
print(a)
#Quiz5
a = [1,2,3,4,5]
b = [8,7,6]
a[3:] = b[::-2]
print(a)

1 (8,)
[0 1 0 0 4]
[ 0  1  2  3 10 10]
[1, 2, 6, 7, 8]
[1, 2, 3, 6, 8]


In [40]:
b = [8,7,6]
print(b[::-2])

[6, 8]


In [41]:
a = np.array([6,9,3,5,7,2,8,1])
print(a)

[6 9 3 5 7 2 8 1]


In [42]:
#using fancy indexing, filter all the odd numbers in a
a[a%2 != 0]

array([9, 3, 5, 7, 1])

In [57]:
# Case-study -> NPS
# NPS => Net Promoter Score 

<img src="https://drive.google.com/uc?id=1-u8e-v_90JdikorKsKzBM-JJqoRtzsN8">

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">

In [45]:
# NPS = %promoters - %Detractors

''' 
%promoters = #of promoters/ total users
'''

' \n%promoters = #of promoters/ total users\n'

In [46]:
score = np.loadtxt("survey.txt", dtype = "int")

In [47]:
print(score)

[ 7 10  5 ...  5  9 10]


In [48]:
len(score)

1167

In [49]:
p_rating = score[score > 8]
print(p_rating)



[10  9  9  9  9  9 10  9  9 10  9  9  9  9  9  9  9 10 10  9 10  9 10  9
  9 10 10  9 10  9 10 10 10  9  9 10 10 10  9 10  9 10  9  9  9 10  9  9
  9  9  9  9 10  9  9  9 10  9 10  9  9  9  9  9 10 10  9 10  9  9 10  9
  9 10  9  9  9  9  9  9  9  9  9  9  9 10  9  9  9  9  9  9  9  9 10  9
  9  9  9  9 10 10  9 10 10 10 10  9 10  9  9  9  9  9  9  9 10  9 10  9
 10  9 10 10 10  9  9 10 10  9  9  9  9 10  9  9  9  9 10 10  9  9  9 10
  9  9  9  9  9 10  9  9  9 10  9 10 10  9  9  9  9 10  9 10  9  9  9  9
 10  9 10  9  9  9  9  9  9  9  9  9  9  9 10 10  9  9  9 10  9 10 10 10
 10 10  9  9  9  9 10 10 10  9  9 10  9 10 10 10 10  9 10 10  9 10  9  9
  9  9 10  9 10  9 10  9  9  9  9 10  9  9  9  9  9 10  9 10 10  9 10 10
 10  9  9  9  9  9  9 10  9  9 10  9 10 10  9  9  9 10 10 10 10  9  9  9
 10 10  9 10  9  9  9 10  9  9  9  9  9  9  9  9  9  9 10  9  9  9 10  9
 10  9 10  9 10  9  9 10 10  9  9  9 10  9  9 10  9  9  9  9  9  9 10 10
  9 10  9  9  9  9 10  9  9  9  9 10  9 10  9 10  9

In [50]:
no_of_promoters = len(p_rating)
print(no_of_promoters)

total = len(score)

perc_promoters = no_of_promoters *100/ total
print(perc_promoters)



609
52.18508997429306


In [53]:
d_rating = score[score < 7]
no_detractors = len(d_rating)

perc_detractors = no_detractors * 100 / total
print(perc_detractors)

28.449014567266495


In [54]:
nps = perc_promoters - perc_detractors
print(nps)

23.73607540702656


In [56]:
np.round(nps,2)

23.74