In [ ]:
# Topics Covered:
#     Sort()
#     np.sort()
#     Matrix Multiplication
#     vectorization of array
#     Braodcasting 

In [1]:
import numpy as np

In [2]:
# sorting 

a = np.array([4,3,6,9,1,2,3])
print(a)

[4 3 6 9 1 2 3]


In [4]:
b = np.sort(a)
b

array([1, 2, 3, 3, 4, 6, 9])

In [5]:
d = np.array([4,3,6,9,1,2,3])
d.sort()
# this sort will change the original variable
d

array([1, 2, 3, 3, 4, 6, 9])

In [6]:
# argsort
# Returns the idx of the array as a list in which it is sorted 
x = np.array([4,3,6,9,1,2,3])
np.argsort(x)


array([4, 5, 1, 6, 0, 2, 3], dtype=int64)

In [7]:
b = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

In [8]:
np.sort(b)

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [9]:
np.sort(b,axis=0)

array([[ 12,   4,   0],
       [ 23,  89,   3],
       [ 69, 420,  43]])

In [12]:
a = np.arange(5)  # int
b = np.ones(5)  # float
c = np.zeros(5)
print(a,b)

[0 1 2 3 4] [1. 1. 1. 1. 1.]


In [11]:
a*b

array([0., 1., 2., 3., 4.])

In [13]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
b = np.arange(2,14).reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [15]:
a + b

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [16]:
a * b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [20]:
# if we change the dimension of the matrix 
a = a.reshape(4,-1)
a * b

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [21]:
# Matrix Multiplication

''' 
    1. np.dot
    2. @ operator
    3. np.matmul
'''



' \n    1. np.dot\n    2. @ operator\n    3. np.matmul\n'

In [26]:
# Matrix Multiplication 

a = np. arange(1,13).reshape(3,4)
b = np.arange(2,14).reshape(4,3)

print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [27]:
c = np.dot(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [28]:
c = a@b
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [29]:
np.matmul(a,b)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [4]:
# Vectorization --> np
a = np.arange(10)


In [6]:
def solve(n):
    if n%2 == 0:
        n += 2
    else:
        n -= 2
    return n

In [7]:
solve(4)

6

In order to apply a function to np array then we have use vectorize.

In [8]:
new_solve = np.vectorize(solve)

In [9]:
new_solve(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

BroadCasting:

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)


(4, 3)  --> 2D

(3)  --> 1D
 |
 |
 V
(1,3)

The rule for broadcast is
Across every dimension:
    1. Same in dimensions.
    2. Atleast one of them should be 1.



In [17]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [18]:
a = np.tile(a,(3,1))
a = a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [27]:
np.tile(a,(3,2)) # Tuple indicates the replication of the matrix in row and column wise 

array([[ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30],
       [ 0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30]])

In [28]:
b = np.arange(0,3)
b = np.tile(b,(4,1))
b


'\nExplanation:\na -> (4,3)\nb -> (3,) --> (1,3)\n\n(4,3)\n(1,3)\n\noutput: (4,3)\n\n'

In [23]:
a + b 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [24]:
# Case 2

'''
Explanation:
a -> (4,3)
b -> (3,) --> (1,3)

(4,3)
(1,3)

output: (4,3)

'''
c = np.arange(0,3)
a+c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [29]:
# Case 3
'''
Explanation:

(4,1)
(3,) --> (1, 3)


(4,1)
(1,3)

output: (4,3)
'''
d = np.arange(0,40,10).reshape(4,1)
d + c 

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [30]:
'''
Quiz

Given two arrays of shape
Array A of shape (8, 1, 6, 1)
Array B of shape (7, 1, 5)
Is broadcasting possible in this case? If yes, what will be the shape of output ?
'''

'''
Soln:

A -> (8, 1, 6, 1)
B -> (7, 1, 5) --> (1, 7, 1, 5)


A -> (8, 1, 6, 1)
B -> (1, 7, 1, 5)

What will be the shape after broadcasting
(8, 7, 6, 5)

'''

'\nSoln:\n\nA -> (8, 1, 6, 1)\nB -> (7, 1, 5) --> (1, 7, 1, 5)\n\n\nA -> (8, 1, 6, 1)\nB -> (1, 7, 1, 5)\n\nWhat will be the shape after broadcasting\n(8, 7, 6, 5)\n\n'

In [32]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [33]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)


array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [34]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

# 1*3 = 1*3

46

In [36]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [37]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [38]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [39]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [44]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [47]:
np.all(birds=='Cranes')

False

In [48]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0

In [49]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])